/* App version (MAJOR.MINOR.PATCH). MAJOR is set by the owner; MINOR (new features, or any change to calculated
 * results) and PATCH (fixes that don't change results, UI and text) are bumped with each change. Newest first.
 * Shown in the header and the About dialog, and written into saved rig files. The original program's license asks
 * every modified version's history to show who made the change, when, and what changed: [version, date, who, what]. */
(function (g) {
  var TLA = (g.TLA = g.TLA || {});
  TLA.VERSION = "1.4.0";
  TLA.CHANGES = [
    ["1.4.0", "2026-09-22", "G.E. Simmons Falk", "Stiffness solve: truss stiffness, shear, trim, hoist springs and semi-rigid corner blocks. Each truss's bending stiffness is now estimated from its manufacturer's tables (the largest table moment carried by its chords; it grows with about depth squared, not depth cubed as before), with shear and torsion stiffness from an estimated diagonal lattice, and real chord/diagonal sizes in the truss data can replace the estimate. Trusses are Timoshenko beams (shear deformation: large on short spans). Corner blocks are also solved as semi-rigid rotational springs (1, 4 and 16 x EI/L) between hinged and rigid, and every check uses the worst. New: the load change on each hoist when it runs 1/4\" high (trim), with a warning past 10% of its capacity; an optional hoist stiffness (lb/in); an export of the stiffness model and tools/pynite_check.py, which rebuilds it in PyNite (the engine behind CalcForge 3D) and compares - it agrees to 0.01 lb on the test rigs. Changes hoist loads and member forces wherever trusses share load (grids, and single trusses on three or more hoists)."],
    ["1.3.0", "2026-09-22", "G.E. Simmons Falk", "The stiffness (grillage) solve of the whole rig is now the primary result instead of a check: hoist loads, the forces in bolted connections, the loads every span and cantilever check sees, and the bending moment and shear the 1.2.0 moment/shear check uses (including moment carried through rigid corner blocks) all come from it. Hinged and rigid joints are shown side by side and every check uses the worse of the two; the load-path numbers of the original workbook are kept as a reference column. Changes results on grids where a carrying truss sags (single trusses on hoists are unchanged). Also: torque along every truss from the stiffness solve, a hoist's load breakdown from the same solve, a self-check that the connection forces balance, and a clear fallback to the load-path method when the stiffness solve can't run."],
    ["1.2.0", "2026-09-22", "G.E. Simmons Falk", "Shear and bending-moment diagrams for every truss, and a moment/shear check against an allowable moment and shear estimated from the manufacturer's tables. It catches what the span-by-span table check can't: bending over the supports of a continuous truss, and heavy loads right next to a support. Can flag trusses the table check passed. The 'count truss weight' option now also applies to this check."],
    ["1.1.0", "2026-09-22", "G.E. Simmons Falk", "Chain hoists can only pull: a hoist the load would push up is now shown as Slack, taken out, and the truss solved again (both the load-path and the stiffness check); a truss or rig that would tip is flagged UNSTABLE instead of showing loads. Changes results where a hoist used to show a negative load. Stiffness check fixes: hardware weight at bolted connections and loads hung on corner blocks were missing; it now checks its own balance and total against the load path, names any truss that isn't held up, and no longer lets a truss on a single hoist pass. Test added for the Rigging Math Made Simple 3D grid example."],
    ["1.0.0", "2026-09-22", "G.E. Simmons Falk", "First numbered release of Truss Grid Analyzer, a web rebuild of Truss Load Analyzer - EOT: truss-grid load paths through corner blocks, plan and 3D views, manufacturer-table span/cantilever checks, hoist checks, the grillage stiffness check (hinged and rigid joints, stiffness estimated per truss connector type), and the license file (LICENSE.md)."]
  ];
})(typeof globalThis !== "undefined" ? globalThis : window);
