/* App version (MAJOR.MINOR.PATCH). MAJOR is set by the owner; MINOR (new features, or any change to calculated
 * results) and PATCH (fixes that don't change results, UI and text) are bumped with each change. Newest first.
 * Shown in the header and the About dialog, and written into saved rig files. The original program's license asks
 * every modified version's history to show who made the change, when, and what changed: [version, date, who, what]. */
(function (g) {
  var TLA = (g.TLA = g.TLA || {});
  TLA.VERSION = "1.9.1";
  TLA.CHANGES = [
    ["1.9.1", "2026-09-23", "G.E. Simmons Falk", "Side panel: the \"Truss and length\" and \"Corner blocks\" sections of a selected truss are now one section, \"Truss, length and corner blocks\", since both set up the same line. Nothing else changes."],
    ["1.9.0", "2026-09-23", "G.E. Simmons Falk", "Hoists can be dragged along their truss in the plan view, in 1\" steps (2 cm in metric), counted from the truss's measuring reference (start, centerline or end) so the distance stays a round number; the position is shown next to the hoist while dragging and the rig is solved again as it moves. Clicking a hoist still just selects it. No calculation changes."],
    ["1.8.0", "2026-09-23", "G.E. Simmons Falk", "Bolted parts check: bolted truss and corner blocks only fit within one manufacturer's truss family, so a truss bolted to a block, a block in a truss run, or a truss bolted straight to another truss is now warned about when the parts don't match (for example JTE 12x12 into a Christie A Type block, or SuperTruss into a General Purpose block), and the bolt is drawn red on the plan. A generic or universal truss bolted to branded parts is warned about too. Generic, universal and custom parts that can't be checked get a note (listed apart, not counted as warnings). Trusses stacked on top or clamped below are not checked - any family can sit on another. Warnings only: nothing is blocked, and no loads or checks change."],
    ["1.7.0", "2026-09-23", "G.E. Simmons Falk", "Metric or imperial: a Units switch in the toolbar (saved with the rig) shows and takes every length, weight, load, moment, hoist speed and size in feet and pounds or in metres and kilograms (kg·m, m/min, mm). It only converts what is shown and typed - the rig is still stored and solved in feet and pounds, so switching changes no result and no truss, hoist or fixture choice. Lengths can be typed as metres, cm or mm (feet-inches still work). Warnings, the hoist table and its CSV copy follow the switch. A custom truss is saved in the units it is entered in (metric trusses keep their own metric table)."],
    ["1.6.0", "2026-09-23", "G.E. Simmons Falk", "Truss database: every truss now records where its numbers come from - the Truss Load Analyzer workbook (TLA, with the version) or the manufacturer's own data sheet (MFG) - and whether its table is native imperial or metric; the Databases tab lists them all. Added from EOT 2.4: Prolyte S36 PRT with and without wheels (EOT 2.4 has their weights swapped; corrected from its own metric rows) and Total Structures Totalite 11.5\", and EOT 2.4's metric database - 101 trusses from CLS, Eurotruss, Global Truss, HOF, Litec, Milos and Prolyte (Eurotruss HD44 left out: no weight). Metric trusses are checked against their own table in whole-metre steps (span rounded up to the next metre) and get the usual 0.85 repetitive-use derate (EOT 2.4 applies none to metric trusses). Their model numbers are no longer read as inches; their size is unknown, so the stiffness solve assumes a 20.5 in box and says so. Added from Tomcat's published data sheets (L/100 deflection-limited, 2024-2026): Light Duty 12x12 Plated, Spigoted, Guardian and Guardian+ (already reduced for repetitive use), Medium Duty 20.5x20.5 Plated and the 20.5 Triangle Plated and Spigoted, with chord sizes where the sheet gives them; a span between table rows uses the next longer row. The workbook's older Tomcat entries are kept alongside for comparison. Existing trusses' numbers are unchanged."],
    ["1.5.0", "2026-09-23", "G.E. Simmons Falk", "Stiffness solve: the tiny twist stiffness that keeps a truss from spinning about its own axis (which nothing loads) is now sized for each joint from that truss's own stiffness, instead of from the stiffest point anywhere in the rig, and the solver's singularity test is likewise relative to each joint. A very short element (a 0.002 ft stub, without shear deformation as in the PyNite export) could make it stiff enough to hold up a soft pipe, and the rig was then wrongly reported UNSTABLE. Hoist loads move by less than 0.00001 lb on the test rigs; a rig can now pass that was falsely flagged. From Truss Load Analyzer - EOT 2.4 (Sogoian, Multi v1.24): the hoist dynamic factor from speed is now fpm / 60 + 1 (16 fpm = 1.267, was fpm / 64 + 1 = 1.25), which raises dynamic loads by about 1.3% at 16 fpm; an optional 'Add %' on hoist loads (the load and truss weight at each hoist, before hoist and chain weight); new trusses Prolyte H30 Verto and the generic Universal 12\"x12\" bolted, 20\"x20\" bolted and 26\" x 30\" PRT, which carry a 0.75 derate on their table capacities. EOT 2.4's span check multiplies the span-table row number by the derate instead of the capacity, which reads a shorter span and skips the derate; that is not copied - capacities are derated as before."],
    ["1.4.0", "2026-09-22", "G.E. Simmons Falk", "Stiffness solve: truss stiffness, shear, trim, hoist springs and semi-rigid corner blocks. Each truss's bending stiffness is now estimated from its manufacturer's tables (the largest table moment carried by its chords; it grows with about depth squared, not depth cubed as before), with shear and torsion stiffness from an estimated diagonal lattice, and real chord/diagonal sizes in the truss data can replace the estimate. Trusses are Timoshenko beams (shear deformation: large on short spans). Corner blocks are also solved as semi-rigid rotational springs (1, 4 and 16 x EI/L) between hinged and rigid, and every check uses the worst. New: the load change on each hoist when it runs 1/4\" high (trim), with a warning past 10% of its capacity; an optional hoist stiffness (lb/in); an export of the stiffness model and tools/pynite_check.py, which rebuilds it in PyNite (the engine behind CalcForge 3D) and compares - it agrees to 0.01 lb on the test rigs. Changes hoist loads and member forces wherever trusses share load (grids, and single trusses on three or more hoists)."],
    ["1.3.0", "2026-09-22", "G.E. Simmons Falk", "The stiffness (grillage) solve of the whole rig is now the primary result instead of a check: hoist loads, the forces in bolted connections, the loads every span and cantilever check sees, and the bending moment and shear the 1.2.0 moment/shear check uses (including moment carried through rigid corner blocks) all come from it. Hinged and rigid joints are shown side by side and every check uses the worse of the two; the load-path numbers of the original workbook are kept as a reference column. Changes results on grids where a carrying truss sags (single trusses on hoists are unchanged). Also: torque along every truss from the stiffness solve, a hoist's load breakdown from the same solve, a self-check that the connection forces balance, and a clear fallback to the load-path method when the stiffness solve can't run."],
    ["1.2.0", "2026-09-22", "G.E. Simmons Falk", "Shear and bending-moment diagrams for every truss, and a moment/shear check against an allowable moment and shear estimated from the manufacturer's tables. It catches what the span-by-span table check can't: bending over the supports of a continuous truss, and heavy loads right next to a support. Can flag trusses the table check passed. The 'count truss weight' option now also applies to this check."],
    ["1.1.0", "2026-09-22", "G.E. Simmons Falk", "Chain hoists can only pull: a hoist the load would push up is now shown as Slack, taken out, and the truss solved again (both the load-path and the stiffness check); a truss or rig that would tip is flagged UNSTABLE instead of showing loads. Changes results where a hoist used to show a negative load. Stiffness check fixes: hardware weight at bolted connections and loads hung on corner blocks were missing; it now checks its own balance and total against the load path, names any truss that isn't held up, and no longer lets a truss on a single hoist pass. Test added for the Rigging Math Made Simple 3D grid example."],
    ["1.0.0", "2026-09-22", "G.E. Simmons Falk", "First numbered release of Truss Grid Analyzer, a web rebuild of Truss Load Analyzer - EOT: truss-grid load paths through corner blocks, plan and 3D views, manufacturer-table span/cantilever checks, hoist checks, the grillage stiffness check (hinged and rigid joints, stiffness estimated per truss connector type), and the license file (LICENSE.md)."]
  ];
})(typeof globalThis !== "undefined" ? globalThis : window);
